-- EXPLORE ALL OBJECTS IN THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.TABLES;


-- EXPLORE ALL COLUMNS IN THE DATABASE
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers';

-- EXPLORE ALL COUNTRIES OUR CUSTOMERS COME FROM
SELECT
	DISTINCT c.Country
FROM gold.dim_customers c


-- BASIC SALES OVERVIEW

-- Check row count
SELECT
	COUNT(*) AS total_sales
FROM gold.fact_sales

-- FIND THE DATE OF THE FIRST AND THE LAST ORDER
-- HOW MANY YEARS OF SALES ARE AVAILABLE
SELECT
	MIN(invoice_date) AS first_sale,
	MAX(invoice_date) AS last_sale,
	DATEDIFF(year, MIN(invoice_date), MAX(invoice_date)) AS year_of_sale
FROM gold.fact_sales

-- Total Revenue
SELECT
	SUM(total_amount) AS total_revenue
FROM gold.fact_sales;

-- Total sales count
SELECT
	COUNT(f.invoice_id) AS Total_sales
FROM gold.fact_sales f;

-- Average Order Value
SELECT
	AVG(total_amount) AS avg_order_value
FROM gold.fact_sales;

-- TIME-BASED ANALYSIS

-- Revenue by year
SELECT
	YEAR(invoice_date) AS sales_year,
	SUM(total_amount) AS yearly_revenue
FROM gold.fact_sales
GROUP BY YEAR(invoice_date)
ORDER BY YEAR(invoice_date)

-- Revenue by month
SELECT
	YEAR(invoice_date) AS sales_year,
	MONTH(invoice_date) AS sales_month,
	SUM(total_amount) AS monthly_sales
FROM gold.fact_sales
GROUP BY YEAR(invoice_date), MONTH(invoice_date)
ORDER BY sales_year, sales_month

-- EMPLOYEE PERFORMANCE

-- Top Performing Employee
SELECT
	CONCAT(e.FirstName, ' ',e.LastName) AS Employee_Name,
	SUM(f.quantity) AS total_quantities,
	COUNT(f.invoice_id) AS total_orders,
	SUM(f.total_amount) AS total_sales
FROM gold.fact_sales f
JOIN gold.dim_employees e
ON f.employee_id = e.employee_id
GROUP BY 
	e.FirstName,
	e.LastName
ORDER BY SUM(f.total_amount) DESC

-- Customer Analysis
SELECT
	f.customer_id,
	SUM(f.total_amount) AS total_spending,
	COUNT(DISTINCT f.invoice_id) AS total_orders,
	SUM(f.quantity) AS total_quantities
FROM gold.fact_sales f
GROUP BY f.customer_id
ORDER BY SUM(f.total_amount)

-- PRODUCT (TRACK) ANALYSIS

-- Top Selling Products
SELECT
	track_id,
	SUM(quantity) AS total_products_sold
FROM gold.fact_sales
GROUP BY track_id
ORDER BY SUM(quantity)


-- FIND HOW MANY ITEMS ARE SOLD
SELECT
	SUM(d.quantity) AS total_items_sold
FROM gold.fact_sales d


-- FIND THE TOTAL NO. OF CUSTOMERS THAT HAVE PLACED AN ORDER
SELECT
	COUNT(DISTINCT s.customer_id) AS customer_id
FROM gold.fact_sales s


-- GENERATE A REPORT THAT SHOWS ALL KEY METRICS OF THE BUSINESS

SELECT 'Total sales' as measure_name, SUM(total_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total items' AS measure_name, SUM(quantity) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Avgerage Sales' AS measure_name, AVG(total_amount) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Orders' AS measure_name, COUNT(DISTINCT invoice_id) AS measure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total tracks' AS measure_name, COUNT(DISTINCT track_id) AS mesaure_value FROM gold.fact_sales
UNION ALL
SELECT 'Total Customers' AS measure_name, COUNT(DISTINCT customer_id) AS mesaure_value FROM gold.fact_sales


-- FIND TOTAL CUSTOMERS BY COUNTRIES
SELECT
	Country,
	COUNT(customer_id) AS total_customers
FROM gold.dim_customers
GROUP BY Country


-- WHAT IS THE AVERAGE COSTS IN EACH Track ?
SELECT
	track_id,
	AVG(total_amount) AS avg_cost
FROM gold.fact_sales
GROUP BY track_id
ORDER BY AVG(total_amount) DESC


-- WHAT IS THE TOTAL REVENUE GENERATED FOR EACH Track ?
SELECT
	track_id,
	SUM(total_amount) AS total_revenue
FROM gold.fact_sales
GROUP BY track_id
ORDER BY SUM(total_amount) DESC


-- WHAT IS THE TOTAL REVENUE GENERATED BY EACH CUSTOMER ?
SELECT
	customer_id,
	SUM(total_amount) AS total_revenue
FROM gold.fact_sales
GROUP BY customer_id
ORDER BY SUM(total_amount) DESC


-- WHAT IS THE DISTRIBUTION OF SOLD ITEMS ACROSS COUNTRIES ?
SELECT
	c.Country,
	COUNT(s.quantity) AS total_items
FROM gold.fact_sales s
JOIN gold.dim_customers c
ON s.customer_id = c.customer_id
GROUP BY c.Country
ORDER BY COUNT(s.track_id) DESC


-- WHICH 5 TRACK GENERATE THE HIGHEST REVENUE ?
SELECT TOP 5
	t.track_name,
	SUM(s.total_amount) AS total_revenue
FROM gold.fact_sales s
JOIN gold.dim_track t
ON s.track_id = t.track_id
GROUP BY t.track_name
ORDER BY SUM(s.total_amount) DESC


-- WHAT ARE THE 5 WORST-PERFORMING TRACK IN TERMS OF SALES ?
SELECT TOP 5
	t.track_name,
	SUM(s.total_amount) AS total_revenue
FROM gold.fact_sales s
JOIN gold.dim_track t
ON s.track_id = t.track_id
GROUP BY t.track_name
ORDER BY SUM(s.total_amount)


-- FIND THE TOP 10 CUSTOMERS WHO HAVE GENERATED THE HIGHEST REVENUE
SELECT TOP 10
	customer_id,
	SUM(total_amount) AS total_revenue
FROM gold.fact_sales
GROUP BY customer_id
ORDER BY SUM(total_amount) DESC


-- FIND THE TOP 3 CUSTOMERS WITH FEWEST ORDERS PLACED
SELECT TOP 3
	customer_id,
	COUNT(DISTINCT invoice_id) AS total_orders
FROM gold.fact_sales
GROUP BY customer_id
ORDER BY COUNT(invoice_id)


-- Revenue per individual customer
WITH CTE AS
(
	SELECT
		c.customer_id AS CustomerId,
		c.Country AS Country,
		SUM(s.total_amount) AS total_revenue
	FROM gold.fact_sales s
	JOIN gold.dim_customers c
	ON s.customer_id = c.customer_id
	GROUP BY c.customer_id, c.Country
) 
SELECT 
	CustomerId,
	Country,
	total_revenue
FROM CTE
ORDER BY total_revenue DESC


-- Which country generates the highest revenue per customer?
WITH CTE AS
(
	SELECT
		c.Country AS Country,
		SUM(s.total_amount) AS total_revenue,
		COUNT(c.customer_id) AS TotalCustomers
	FROM gold.fact_sales s
	JOIN gold.dim_customers c
	ON s.customer_id = c.customer_id
	GROUP BY c.Country
) 
SELECT 
	TotalCustomers,
	Country,
	total_revenue * 1.0 / TotalCustomers AS revenue_per_customer
FROM CTE
ORDER BY total_revenue DESC


-- Which 3 tracks generate the most revenue in each country?
WITH CTE AS
(
	SELECT
		t.track_name AS TrackName,
		c.Country AS Country,
		SUM(s.total_amount) AS total_revenue
	FROM gold.fact_sales s
	JOIN gold.dim_customers c
	ON s.customer_id = c.customer_id
	JOIN gold.dim_track t
	ON s.track_id = t.track_id
	GROUP BY t.track_name, c.Country
),
Rankedsales AS (
	SELECT
		RANK() OVER(PARTITION BY Country ORDER BY total_revenue DESC) AS Row_Count,
		TrackName,
		Country,
		total_revenue
	FROM CTE
)
SELECT 
*
FROM Rankedsales
WHERE Row_Count <= 3
